spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop


server:
  port: 9080
  servlet:
    context-path: '/kontakt'


